version: 2.1

orbs:
  node: circleci/node@5

jobs:
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Print folder structure
          command: ls -R  # Print the entire folder structure recursively

  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies in the root folder
          command: npm install
      - run:
          name: Install dependencies in the client folder
          command: cd client && npm install
      - run:
          name: Build React app
          command: cd client && npm run build
      - run:
          name: Build the client and server
          command: npm run build
      - run:
          name: Install Vercel CLI
          command: npm install vercel
      - run:
          name: Deploy to Vercel
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID ./node_modules/.bin/vercel --token $VERCEL_TOKEN --prod --yes;
            else
              VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID ./node_modules/.bin/vercel --token $VERCEL_TOKEN --yes;
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - build_and_deploy:
          requires:
            - install_dependencies
